name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  go-checks:
    name: Go Checks
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: orders

    steps:
      - uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.21'
          cache: true

      - name: Install dependencies
        run: go mod download

      - name: Run vet
        run: go vet ./...

      - name: Run tests
        run: go test -v ./... -short

  node-checks:
    name: Node.js Checks
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: notifications

    steps:
      - uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'
          cache: 'npm'
          cache-dependency-path: notifications/package-lock.json

      - name: Install dependencies
        run: npm ci

      - name: Run linter
        run: npm run lint

      - name: Run tests
        run: npm test

  integration-tests:
    name: Integration Tests
    runs-on: ubuntu-latest
    needs: [go-checks, node-checks]

    services:
      localstack:
        image: localstack/localstack:latest
        env:
          SERVICES: sns,sqs
          AWS_DEFAULT_REGION: us-east-1
          EDGE_PORT: 4566
          AWS_ACCESS_KEY_ID: test
          AWS_SECRET_ACCESS_KEY: test
        ports:
          - 4566:4566
        options: >-
          --health-cmd "curl -f http://localhost:4566/_localstack/health"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
      - uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.21'
          cache: true

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'
          cache: 'npm'
          cache-dependency-path: notifications/package-lock.json

      - name: Install jq
        run: sudo apt-get update && sudo apt-get install -y jq

      - name: Install Go dependencies
        working-directory: orders
        run: go mod download

      - name: Install Node.js dependencies
        working-directory: notifications
        run: npm ci

      - name: Set up AWS environment
        run: |
          echo "AWS_ACCESS_KEY_ID=test" >> $GITHUB_ENV
          echo "AWS_SECRET_ACCESS_KEY=test" >> $GITHUB_ENV
          echo "AWS_DEFAULT_REGION=us-east-1" >> $GITHUB_ENV
          echo "AWS_ENDPOINT_URL=http://localhost:4566" >> $GITHUB_ENV

      - name: Wait for LocalStack
        run: |
          timeout 30 bash -c 'until curl -s http://localhost:4566/health; do sleep 1; done'
          sleep 5

      - name: Set up infrastructure
        run: |
          chmod +x scripts/setup-local-aws.sh
          ./scripts/setup-local-aws.sh

      - name: Run Orders E2E tests
        working-directory: orders
        run: go test -v ./tests/e2e/...

      - name: Run Notifications E2E tests
        working-directory: notifications
        run: npm run test:dlq

  required-checks:
    name: Required Checks
    needs: [go-checks, node-checks, integration-tests]
    runs-on: ubuntu-latest
    steps:
      - name: All checks passed
        run: echo "✅ All required checks passed"